export const countries = [
  { id: "india", name: "India" },
  { id: "usa", name: "United States" },
  { id: "uk", name: "United Kingdom" },
  { id: "canada", name: "Canada" },
  { id: "australia", name: "Australia" },
  { id: "germany", name: "Germany" },
  { id: "france", name: "France" },
  { id: "japan", name: "Japan" },
  { id: "brazil", name: "Brazil" },
  { id: "south-africa", name: "South Africa" },
];

export const states = {
  india: [
    { id: "maharashtra", name: "Maharashtra" },
    { id: "karnataka", name: "Karnataka" },
    { id: "tamil-nadu", name: "Tamil Nadu" },
    { id: "delhi", name: "Delhi" },
    { id: "gujarat", name: "Gujarat" },
  ],
  usa: [
    { id: "california", name: "California" },
    { id: "new-york", name: "New York" },
    { id: "texas", name: "Texas" },
    { id: "florida", name: "Florida" },
    { id: "illinois", name: "Illinois" },
  ],
  uk: [
    { id: "england", name: "England" },
    { id: "scotland", name: "Scotland" },
    { id: "wales", name: "Wales" },
    { id: "northern-ireland", name: "Northern Ireland" },
  ],
  canada: [
    { id: "ontario", name: "Ontario" },
    { id: "quebec", name: "Quebec" },
    { id: "british-columbia", name: "British Columbia" },
    { id: "alberta", name: "Alberta" },
    { id: "manitoba", name: "Manitoba" },
  ],
  australia: [
    { id: "new-south-wales", name: "New South Wales" },
    { id: "victoria", name: "Victoria" },
    { id: "queensland", name: "Queensland" },
    { id: "western-australia", name: "Western Australia" },
    { id: "south-australia", name: "South Australia" },
  ],
  germany: [
    { id: "bavaria", name: "Bavaria" },
    { id: "north-rhine-westphalia", name: "North Rhine-Westphalia" },
    { id: "baden-wurttemberg", name: "Baden-Württemberg" },
    { id: "lower-saxony", name: "Lower Saxony" },
    { id: "hesse", name: "Hesse" },
  ],
  france: [
    { id: "ile-de-france", name: "Île-de-France" },
    { id: "auvergne-rhone-alpes", name: "Auvergne-Rhône-Alpes" },
    { id: "nouvelle-aquitaine", name: "Nouvelle-Aquitaine" },
    { id: "occitanie", name: "Occitanie" },
    { id: "hauts-de-france", name: "Hauts-de-France" },
  ],
  japan: [
    { id: "tokyo", name: "Tokyo" },
    { id: "osaka", name: "Osaka" },
    { id: "aichi", name: "Aichi" },
    { id: "hokkaido", name: "Hokkaido" },
    { id: "fukuoka", name: "Fukuoka" },
  ],
  brazil: [
    { id: "sao-paulo", name: "São Paulo" },
    { id: "rio-de-janeiro", name: "Rio de Janeiro" },
    { id: "minas-gerais", name: "Minas Gerais" },
    { id: "bahia", name: "Bahia" },
    { id: "parana", name: "Paraná" },
  ],
  "south-africa": [
    { id: "gauteng", name: "Gauteng" },
    { id: "western-cape", name: "Western Cape" },
    { id: "kwazulu-natal", name: "KwaZulu-Natal" },
    { id: "eastern-cape", name: "Eastern Cape" },
    { id: "free-state", name: "Free State" },
  ],
};

export const cities = {
  maharashtra: [
    { id: "mumbai", name: "Mumbai" },
    { id: "pune", name: "Pune" },
    { id: "nagpur", name: "Nagpur" },
    { id: "nashik", name: "Nashik" },
    { id: "aurangabad", name: "Aurangabad" },
  ],
  karnataka: [
    { id: "bangalore", name: "Bangalore" },
    { id: "mysore", name: "Mysore" },
    { id: "hubli", name: "Hubli" },
    { id: "mangalore", name: "Mangalore" },
    { id: "belgaum", name: "Belgaum" },
  ],
  "tamil-nadu": [
    { id: "chennai", name: "Chennai" },
    { id: "coimbatore", name: "Coimbatore" },
    { id: "madurai", name: "Madurai" },
    { id: "tiruchirappalli", name: "Tiruchirappalli" },
    { id: "salem", name: "Salem" },
  ],
  delhi: [
    { id: "new-delhi", name: "New Delhi" },
    { id: "north-delhi", name: "North Delhi" },
    { id: "south-delhi", name: "South Delhi" },
    { id: "east-delhi", name: "East Delhi" },
    { id: "west-delhi", name: "West Delhi" },
  ],
  gujarat: [
    { id: "ahmedabad", name: "Ahmedabad" },
    { id: "surat", name: "Surat" },
    { id: "vadodara", name: "Vadodara" },
    { id: "rajkot", name: "Rajkot" },
    { id: "bhavnagar", name: "Bhavnagar" },
  ],
  california: [
    { id: "los-angeles", name: "Los Angeles" },
    { id: "san-francisco", name: "San Francisco" },
    { id: "san-diego", name: "San Diego" },
    { id: "san-jose", name: "San Jose" },
    { id: "fresno", name: "Fresno" },
  ],
  "new-york": [
    { id: "new-york-city", name: "New York City" },
    { id: "buffalo", name: "Buffalo" },
    { id: "rochester", name: "Rochester" },
    { id: "yonkers", name: "Yonkers" },
    { id: "syracuse", name: "Syracuse" },
  ],
  texas: [
    { id: "houston", name: "Houston" },
    { id: "san-antonio", name: "San Antonio" },
    { id: "dallas", name: "Dallas" },
    { id: "austin", name: "Austin" },
    { id: "fort-worth", name: "Fort Worth" },
  ],
  florida: [
    { id: "jacksonville", name: "Jacksonville" },
    { id: "miami", name: "Miami" },
    { id: "tampa", name: "Tampa" },
    { id: "orlando", name: "Orlando" },
    { id: "st-petersburg", name: "St. Petersburg" },
  ],
  illinois: [
    { id: "chicago", name: "Chicago" },
    { id: "aurora", name: "Aurora" },
    { id: "naperville", name: "Naperville" },
    { id: "rockford", name: "Rockford" },
    { id: "joliet", name: "Joliet" },
  ],
  england: [
    { id: "london", name: "London" },
    { id: "manchester", name: "Manchester" },
    { id: "birmingham", name: "Birmingham" },
    { id: "liverpool", name: "Liverpool" },
    { id: "leeds", name: "Leeds" },
  ],
  scotland: [
    { id: "glasgow", name: "Glasgow" },
    { id: "edinburgh", name: "Edinburgh" },
    { id: "aberdeen", name: "Aberdeen" },
    { id: "dundee", name: "Dundee" },
    { id: "inverness", name: "Inverness" },
  ],
  wales: [
    { id: "cardiff", name: "Cardiff" },
    { id: "swansea", name: "Swansea" },
    { id: "newport", name: "Newport" },
    { id: "bangor", name: "Bangor" },
    { id: "wrexham", name: "Wrexham" },
  ],
  "northern-ireland": [
    { id: "belfast", name: "Belfast" },
    { id: "derry", name: "Derry" },
    { id: "lisburn", name: "Lisburn" },
    { id: "newry", name: "Newry" },
    { id: "armagh", name: "Armagh" },
  ],
  ontario: [
    { id: "toronto", name: "Toronto" },
    { id: "ottawa", name: "Ottawa" },
    { id: "mississauga", name: "Mississauga" },
    { id: "brampton", name: "Brampton" },
    { id: "hamilton", name: "Hamilton" },
  ],
  quebec: [
    { id: "montreal", name: "Montreal" },
    { id: "quebec-city", name: "Quebec City" },
    { id: "laval", name: "Laval" },
    { id: "gatineau", name: "Gatineau" },
    { id: "longueuil", name: "Longueuil" },
  ],
  "british-columbia": [
    { id: "vancouver", name: "Vancouver" },
    { id: "victoria", name: "Victoria" },
    { id: "surrey", name: "Surrey" },
    { id: "burnaby", name: "Burnaby" },
    { id: "richmond", name: "Richmond" },
  ],
  alberta: [
    { id: "calgary", name: "Calgary" },
    { id: "edmonton", name: "Edmonton" },
    { id: "red-deer", name: "Red Deer" },
    { id: "lethbridge", name: "Lethbridge" },
    { id: "wood-buffalo", name: "Wood Buffalo" },
  ],
  manitoba: [
    { id: "winnipeg", name: "Winnipeg" },
    { id: "brandon", name: "Brandon" },
    { id: "steinbach", name: "Steinbach" },
    { id: "thompson", name: "Thompson" },
    { id: "portage-la-prairie", name: "Portage la Prairie" },
  ],
  "new-south-wales": [
    { id: "sydney", name: "Sydney" },
    { id: "newcastle", name: "Newcastle" },
    { id: "wollongong", name: "Wollongong" },
    { id: "coffs-harbour", name: "Coffs Harbour" },
    { id: "wagga-wagga", name: "Wagga Wagga" },
  ],
  victoria: [
    { id: "melbourne", name: "Melbourne" },
    { id: "geelong", name: "Geelong" },
    { id: "ballarat", name: "Ballarat" },
    { id: "bendigo", name: "Bendigo" },
    { id: "shepparton", name: "Shepparton" },
  ],
  queensland: [
    { id: "brisbane", name: "Brisbane" },
    { id: "gold-coast", name: "Gold Coast" },
    { id: "sunshine-coast", name: "Sunshine Coast" },
    { id: "townsville", name: "Townsville" },
    { id: "cairns", name: "Cairns" },
  ],
  "western-australia": [
    { id: "perth", name: "Perth" },
    { id: "bunbury", name: "Bunbury" },
    { id: "geraldton", name: "Geraldton" },
    { id: "kalgoorlie", name: "Kalgoorlie" },
    { id: "albany", name: "Albany" },
  ],
  "south-australia": [
    { id: "adelaide", name: "Adelaide" },
    { id: "mount-gambier", name: "Mount Gambier" },
    { id: "whyalla", name: "Whyalla" },
    { id: "port-augusta", name: "Port Augusta" },
    { id: "port-lincoln", name: "Port Lincoln" },
  ],
  bavaria: [
    { id: "munich", name: "Munich" },
    { id: "nuremberg", name: "Nuremberg" },
    { id: "augsburg", name: "Augsburg" },
    { id: "regensburg", name: "Regensburg" },
    { id: "ingolstadt", name: "Ingolstadt" },
  ],
  "north-rhine-westphalia": [
    { id: "cologne", name: "Cologne" },
    { id: "dusseldorf", name: "Düsseldorf" },
    { id: "dortmund", name: "Dortmund" },
    { id: "essen", name: "Essen" },
    { id: "duisburg", name: "Duisburg" },
  ],
  "baden-wurttemberg": [
    { id: "stuttgart", name: "Stuttgart" },
    { id: "karlsruhe", name: "Karlsruhe" },
    { id: "mannheim", name: "Mannheim" },
    { id: "freiburg", name: "Freiburg" },
    { id: "heidelberg", name: "Heidelberg" },
  ],
  "lower-saxony": [
    { id: "hanover", name: "Hanover" },
    { id: "braunschweig", name: "Braunschweig" },
    { id: "osnabruck", name: "Osnabrück" },
    { id: "oldenburg", name: "Oldenburg" },
    { id: "wolfsburg", name: "Wolfsburg" },
  ],
  hesse: [
    { id: "frankfurt", name: "Frankfurt" },
    { id: "wiesbaden", name: "Wiesbaden" },
    { id: "kassel", name: "Kassel" },
    { id: "darmstadt", name: "Darmstadt" },
    { id: "offenbach", name: "Offenbach" },
  ],
  "ile-de-france": [
    { id: "paris", name: "Paris" },
    { id: "boulogne-billancourt", name: "Boulogne-Billancourt" },
    { id: "saint-denis", name: "Saint-Denis" },
    { id: "argenteuil", name: "Argenteuil" },
    { id: "versailles", name: "Versailles" },
  ],
  "auvergne-rhone-alpes": [
    { id: "lyon", name: "Lyon" },
    { id: "saint-etienne", name: "Saint-Étienne" },
    { id: "grenoble", name: "Grenoble" },
    { id: "clermont-ferrand", name: "Clermont-Ferrand" },
    { id: "villeurbanne", name: "Villeurbanne" },
  ],
  "nouvelle-aquitaine": [
    { id: "bordeaux", name: "Bordeaux" },
    { id: "limoges", name: "Limoges" },
    { id: "poitiers", name: "Poitiers" },
    { id: "pau", name: "Pau" },
    { id: "la-rochelle", name: "La Rochelle" },
  ],
  occitanie: [
    { id: "toulouse", name: "Toulouse" },
    { id: "montpellier", name: "Montpellier" },
    { id: "nimes", name: "Nîmes" },
    { id: "perpignan", name: "Perpignan" },
    { id: "beziers", name: "Béziers" },
  ],
  "hauts-de-france": [
    { id: "lille", name: "Lille" },
    { id: "amiens", name: "Amiens" },
    { id: "roubaix", name: "Roubaix" },
    { id: "tourcoing", name: "Tourcoing" },
    { id: "dunkirk", name: "Dunkirk" },
  ],
  tokyo: [
    { id: "shinjuku", name: "Shinjuku" },
    { id: "shibuya", name: "Shibuya" },
    { id: "minato", name: "Minato" },
    { id: "chiyoda", name: "Chiyoda" },
    { id: "chuo", name: "Chūō" },
  ],
  osaka: [
    { id: "osaka-city", name: "Osaka City" },
    { id: "sakai", name: "Sakai" },
    { id: "higashiosaka", name: "Higashiosaka" },
    { id: "takatsuki", name: "Takatsuki" },
    { id: "toyonaka", name: "Toyonaka" },
  ],
  aichi: [
    { id: "nagoya", name: "Nagoya" },
    { id: "toyota", name: "Toyota" },
    { id: "okazaki", name: "Okazaki" },
    { id: "ichinomiya", name: "Ichinomiya" },
    { id: "kasugai", name: "Kasugai" },
  ],
  hokkaido: [
    { id: "sapporo", name: "Sapporo" },
    { id: "asahikawa", name: "Asahikawa" },
    { id: "hakodate", name: "Hakodate" },
    { id: "obihiro", name: "Obihiro" },
    { id: "kushiro", name: "Kushiro" },
  ],
  fukuoka: [
    { id: "fukuoka-city", name: "Fukuoka City" },
    { id: "kitakyushu", name: "Kitakyushu" },
    { id: "kurume", name: "Kurume" },
    { id: "kasuga", name: "Kasuga" },
    { id: "iizuka", name: "Iizuka" },
  ],
  "sao-paulo": [
    { id: "sao-paulo-city", name: "São Paulo City" },
    { id: "campinas", name: "Campinas" },
    { id: "guarulhos", name: "Guarulhos" },
    { id: "santos", name: "Santos" },
    { id: "sao-bernardo-do-campo", name: "São Bernardo do Campo" },
  ],
  "rio-de-janeiro": [
    { id: "rio-de-janeiro-city", name: "Rio de Janeiro City" },
    { id: "niteroi", name: "Niterói" },
    { id: "duque-de-caxias", name: "Duque de Caxias" },
    { id: "nova-iguacu", name: "Nova Iguaçu" },
    { id: "belford-roxo", name: "Belford Roxo" },
  ],
  "minas-gerais": [
    { id: "belo-horizonte", name: "Belo Horizonte" },
    { id: "uberlandia", name: "Uberlândia" },
    { id: "contagem", name: "Contagem" },
    { id: "juiz-de-fora", name: "Juiz de Fora" },
    { id: "betim", name: "Betim" },
  ],
  bahia: [
    { id: "salvador", name: "Salvador" },
    { id: "feira-de-santana", name: "Feira de Santana" },
    { id: "vitoria-da-conquista", name: "Vitória da Conquista" },
    { id: "camaçari", name: "Camaçari" },
    { id: "itabuna", name: "Itabuna" },
  ],
  parana: [
    { id: "curitiba", name: "Curitiba" },
    { id: "londrina", name: "Londrina" },
    { id: "maringa", name: "Maringá" },
    { id: "ponta-grossa", name: "Ponta Grossa" },
    { id: "cascavel", name: "Cascavel" },
  ],
  gauteng: [
    { id: "johannesburg", name: "Johannesburg" },
    { id: "pretoria", name: "Pretoria" },
    { id: "ekurhuleni", name: "Ekurhuleni" },
    { id: "soweto", name: "Soweto" },
    { id: "centurion", name: "Centurion" },
  ],
  "western-cape": [
    { id: "cape-town", name: "Cape Town" },
    { id: "stellenbosch", name: "Stellenbosch" },
    { id: "paarl", name: "Paarl" },
    { id: "george", name: "George" },
    { id: "worcester", name: "Worcester" },
  ],
  "kwazulu-natal": [
    { id: "durban", name: "Durban" },
    { id: "pietermaritzburg", name: "Pietermaritzburg" },
    { id: "richards-bay", name: "Richards Bay" },
    { id: "newcastle", name: "Newcastle" },
    { id: "ladysmith", name: "Ladysmith" },
  ],
  "eastern-cape": [
    { id: "port-elizabeth", name: "Port Elizabeth" },
    { id: "east-london", name: "East London" },
    { id: "uitenhage", name: "Uitenhage" },
    { id: "mthatha", name: "Mthatha" },
    { id: "grahamstown", name: "Grahamstown" },
  ],
  "free-state": [
    { id: "bloemfontein", name: "Bloemfontein" },
    { id: "welkom", name: "Welkom" },
    { id: "bethlehem", name: "Bethlehem" },
    { id: "sasolburg", name: "Sasolburg" },
    { id: "parys", name: "Parys" },
  ],
};
